language: c

notifications:
  email: false

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
    --no-install-recommends
    clang
    libjson-glib-dev
    libpurple-dev

script:
  - CFLAGS="-Wall" ./autogen.sh
  - scan-build -k
      --use-cc=$(which "${CC}")
      --status-bugs
      -analyze-headers
      make
