language: c

notifications:
  email: false

os:
  - linux

compiler:
  - gcc

env:
  - ANALYZER=""
  - ANALYZER="scan-build -k --status-bugs"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
    --no-install-recommends
    clang
    libjson-glib-dev
    libpurple-dev

script:
  - CFLAGS="-Werror" ./autogen.sh --enable-warnings
  - ${ANALYZER} make
