language: c

notifications:
  email: false

os:
  - linux

compiler:
  - gcc

env:
  - DEBUG=disable
  - DEBUG=enable

before_install:
  - sudo add-apt-repository -y ppa:pidgin-developers/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq
    --no-install-recommends
    clang
    libjson-glib-dev
    libpurple-dev

script:
  - ./autogen.sh --${DEBUG}-debug
  - scan-build -k
      --use-cc=$(which "${CC}")
      --status-bugs
      -analyze-headers
      make
